# 配置文件 .servers.yaml

# 服务器配置
- name: main
  # 添加接收信息的端点
  receive:
    method: ws  # 正向ws或reverse ws
    url: ws://127.0.0.1:10012/ws  # 你的接收端点URL
  # 添加发送信息的端点
  send:
    method: http  # 可以是ws, reverse ws, 或 http
    url: http://127.0.0.1:10013/send  # 你的发送端点URL

# 其他服务器配置
- name: other
  # 添加接收信息的端点
  receive:
    method: reverse ws
    url: ws://127.0.0.1:10014/ws
  # 添加发送信息的端点
  send:
    method: ws
    url: ws://127.0.0.1:10015/ws
