# 配置文件 .servers.yaml

# 服务器配置
- name: main
  # 添加接收信息的端点
  receive:
    method: ws  # 正向ws或reverse_ws
    url: ws://127.0.0.1:10012/ws  # 你的接收端点URL
  # 添加发送信息的端点
  send:
    method: http  # 可以是 http 或与接收方一致，如果为same，则无需配置url
    url: http://127.0.0.1:10013  # 你的发送端点URL

# 其他服务器配置
- name: other
  # 添加接收信息的端点
  receive:
    method: reverse_ws
    url: ws://127.0.0.1:10014/ws
  # 添加发送信息的端点
  send:
    method: same # 可以是 http 或与接收方一致，如果为same，则无需配置url
